# Generated by Django 6.0.3 on 2026-03-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facility_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('physio', 'Physiotherapist'), ('call_center', 'Call Center'), ('billing', 'Billing')], default='call_center', max_length=20),
        ),
    ]
