# Generated by Django 6.0.2 on 2026-03-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_facility_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('physio', 'Physiotherapist'), ('call_center', 'Call Center Agent'), ('billing', 'Receptionist'), ('billing', 'Approvals Controller'), ('billing', 'RCM Controller'), ('billing', 'Visitor')], default='Visitor', max_length=20),
        ),
    ]
