# Generated by Django 6.0.3 on 2026-03-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reception', 'Receptionist'), ('physiotherapist', 'Physiotherapist'), ('callcenter', 'Call Center'), ('approvals', 'Approvals'), ('rcm', 'RCM'), ('visitors', 'Visitors'), ('admin', 'Admin')], default='visitors', max_length=20),
        ),
    ]
