# Generated by Django 5.2.12 on 2026-03-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("physio", "Physio"),
                    ("reception", "Reception"),
                    ("visitor", "Visitor"),
                    ("doctor", "Doctor"),
                    ("rcm", "RCM"),
                    ("callcenter", "Call Center"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
