# Generated by Django 5.2.12 on 2026-03-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("approvals", "Approvals"),
                    ("physio", "Physio"),
                    ("reception", "Reception"),
                    ("reception_supervisor", "Reception Supervisor"),
                    ("visitor", "Visitor"),
                    ("visitor_ceo", "Visitor CEO"),
                    ("doctor", "Doctor"),
                    ("rcm", "RCM"),
                    ("callcenter", "Call Center"),
                    ("callcenter_supervisor", "Call Center Supervisor"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
