# Generated by Django 5.2.12 on 2026-04-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="attendance_status",
            field=models.CharField(
                choices=[("no_show", "No Show"), ("attended", "Attended")],
                default="no_show",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="attended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
