# Generated by Django 5.2.12 on 2026-04-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0003_waitinglistentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waitinglistentry",
            name="preferred_time",
        ),
        migrations.AddField(
            model_name="waitinglistentry",
            name="preferred_time_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("evening", "Evening"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
