# Generated by Django 5.2.12 on 2026-04-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0004_remove_waitinglistentry_preferred_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitinglistentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("notified", "Notified"),
                    ("booked", "Booked"),
                    ("cancelled", "Cancelled"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
