# Generated by Django 5.2.12 on 2026-04-28 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("callcenter", "0005_alter_waitinglistentry_status"),
        ("patients", "0007_patient_registered_at_patient_registered_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="waitinglistentry",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="waitinglistentry",
            name="preferred_time_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Any Time"),
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("evening", "Evening"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(
                fields=["status", "created_at"], name="callcenter__status_77f32a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(
                fields=["preferred_date", "status"],
                name="callcenter__preferr_6dd027_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(
                fields=["created_by", "status"], name="callcenter__created_5a46bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="waitinglistentry",
            index=models.Index(
                fields=["preferred_therapist", "status"],
                name="callcenter__preferr_d5558b_idx",
            ),
        ),
    ]
