# Generated by Django 5.2.12 on 2026-03-30 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0004_patient_created_at_patient_current_approval_number_and_more",
        ),
        ("reception", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="patients.patient",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        limit_choices_to={"role": "physio"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapist_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["assignment_date", "created_at"],
            },
        ),
        migrations.DeleteModel(
            name="TherapySession",
        ),
    ]
