# Generated by Django 5.2.12 on 2026-03-31 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0003_patientassignment_delete_therapysession"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientassignment",
            options={"ordering": ["-assignment_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="patientassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
