# Generated by Django 5.2.12 on 2026-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0004_alter_patientassignment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientassignment",
            name="category",
            field=models.CharField(
                choices=[
                    ("appointment", "Has Appointment"),
                    ("walk_in", "Walk In"),
                    ("initial_evaluation", "Initial Evaluation"),
                    ("task_without_eligibility", "Task Without Eligibility"),
                ],
                default="appointment",
                max_length=40,
            ),
        ),
    ]
