# Generated by Django 5.2.12 on 2026-04-01 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_rename_sessions_taken_patient_approved_sessions_and_more"),
        ("reception", "0005_patientassignment_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patientassignment",
            constraint=models.UniqueConstraint(
                fields=("patient", "assignment_date"),
                name="unique_patient_assignment_per_day",
            ),
        ),
    ]
