# Generated by Django 6.0.3 on 2026-03-07 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_file_number_alter_patient_full_name'),
        ('therapy_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapysession',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='therapysession',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_sessions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='session_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='therapist',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'physiotherapist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
