# Generated by Django 5.2.12 on 2026-03-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="full_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="file_number",
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
