# Generated by Django 5.2.12 on 2026-04-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0004_patient_created_at_patient_current_approval_number_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="sessions_taken",
            new_name="approved_sessions",
        ),
        migrations.AddField(
            model_name="patient",
            name="booking",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="number_of_evaluations",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="utilized_sessions",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
