# Generated by Django 6.0.3 on 2026-03-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
