# Generated by Django 5.2.12 on 2026-04-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_rename_sessions_taken_patient_approved_sessions_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="number_of_evaluations",
            new_name="sessions_taken",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="booking",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="utilized_sessions",
        ),
        migrations.AddField(
            model_name="patient",
            name="approval_expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="approval_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="approved_cpt_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="patient",
            name="insurance_provider",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
