# Generated by Django 5.2.12 on 2026-04-02 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0005_rename_sessions_taken_patient_approved_sessions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceBillingCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_provider",
                    models.CharField(
                        choices=[("thiqa", "Thiqa")], default="thiqa", max_length=30
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["insurance_provider", "code"],
                "unique_together": {("insurance_provider", "code")},
            },
        ),
        migrations.CreateModel(
            name="PatientApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_provider",
                    models.CharField(
                        choices=[("thiqa", "Thiqa")], default="thiqa", max_length=30
                    ),
                ),
                (
                    "authorization_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("approved_sessions", models.PositiveIntegerField(default=0)),
                ("approved_cpt_codes", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_record",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
