# Generated by Django 5.2.12 on 2026-04-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_approvalhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insurancebillingcode",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="insurancebillingcode",
            name="description",
        ),
        migrations.AddField(
            model_name="insurancebillingcode",
            name="default_sessions",
            field=models.PositiveIntegerField(default=6),
        ),
    ]
